import { t, type Dictionary } from "intlayer";

const pageContent = {
  key: "health-section",
  content: {
    title: t({
      en: "Health: The Body as a Mirror of Nature's Justice",
      tr: "Sağlık: Doğadaki Adaletin Aynası Olarak Vücut",
      de: "Gesundheit: Der Körper als Spiegel der Gerechtigkeit der Natur",
      fr: "Santé : Le corps comme miroir de la justice de la nature"
    }),
    quote: t({
      en: "The human body itself proves the logic to be observed.\nOur physical and mental health directly reflects alignment with nature's justice and the quality of our relationships.",
      tr: "İnsan bedeni, gözlemlenmesi gereken mantığı bizzat kanıtlar.\nFiziksel ve zihinsel sağlığımız, doğanın adaletiyle uyumumuzu ve ilişkilerimizin niteliğini doğrudan yansıtır.",
      de: "Der menschliche Körper selbst beweist die Logik, die zu beachten ist.\nUnsere körperliche und geistige Gesundheit spiegelt direkt die Übereinstimmung mit der Gerechtigkeit der Natur und die Qualität unserer Beziehungen wider.",
      fr: "Le corps humain lui-même prouve la logique à observer.\nNotre santé physique et mentale reflète directement l’alignement avec la justice de la nature et la qualité de nos relations."
    }),
    description: t({
      en: "Qualities like compassion, honesty, forgiveness, and support for others strengthen our organs, mental resilience, and overall well-being. Negative or harmful actions disrupt balance, weaken the body, and manifest as illness or stress.\n\nNothing is random in nature: Every disease explains (y)our misalignments — consequences of your actions.\n\nActions can be both inward and outward in any relationship. **Your relationship with yourself is equally important as your relationships with others.**",
      tr: "Merhamet, dürüstlük, affetme ve başkalarına yardım etme gibi nitelikler, organlarımızı, zihinsel dayanıklılığımızı ve genel sağlığımızı güçlendirir. Olumsuz veya zararlı eylemler dengeyi bozar, bedeni zayıflatır ve hastalık veya stres olarak kendini gösterir.\n\nDoğada hiçbir şey rastgele değildir: Her hastalık, uyumsuzluklarımızı — eylemlerimizin sonuçlarını — açıklar.\n\nEylemler, herhangi bir ilişkide hem içe hem dışa yönelik olabilir. **Kendinizle olan ilişkiniz, başkalarıyla olan ilişkileriniz kadar önemlidir.**",
      de: "Eigenschaften wie Mitgefühl, Ehrlichkeit, Vergebung und Unterstützung für andere stärken unsere Organe, unsere mentale Widerstandsfähigkeit und unser allgemeines Wohlbefinden. Negative oder schädliche Handlungen stören das Gleichgewicht, schwächen den Körper und zeigen sich als Krankheit oder Stress.\n\nIn der Natur ist nichts zufällig: Jede Krankheit erklärt unsere Fehlanpassungen — die Folgen unserer Handlungen.\n\nHandlungen können in jeder Beziehung sowohl nach innen als auch nach außen gerichtet sein. **Ihre Beziehung zu sich selbst ist genauso wichtig wie Ihre Beziehungen zu anderen.**",
      fr: "Des qualités comme la compassion, l’honnêteté, le pardon et le soutien aux autres renforcent nos organes, notre résilience mentale et notre bien-être global. Les actions négatives ou nuisibles perturbent l’équilibre, affaiblissent le corps et se manifestent sous forme de maladie ou de stress.\n\nRien n’est aléatoire dans la nature : chaque maladie explique nos désalignements — conséquences de nos actions.\n\nLes actions peuvent être à la fois intérieures et extérieures dans toute relation. **Votre relation avec vous-même est aussi importante que vos relations avec les autres.**"
    }),
    analogy: {
      title: t({
        en: "Organ-Action-Consequence Analogy",
        tr: "Organ-Eylem-Sonuç Benzetmesi",
        de: "Organ-Handlung-Folge-Analogie",
        fr: "Analogie Organe-Action-Conséquence"
      }),
      quote: t({
        en: "Body organs function like members of a society, each with a specific role reflecting the harmony — or imbalance — of our choices in nature. Their condition combined with their purpose offers silent guidance.",
        tr: "Vücut organları, toplumdaki bireyler gibi işlev görür; her biri, doğadaki seçimlerimizin uyumunu veya dengesizliğini yansıtan özel bir role sahiptir. Sağlık durumları ve işleyiş amaçları bir araya geldiğinde size sessiz bir rehberlik sunarlar.",
        de: "Körperorgane funktionieren wie Mitglieder einer Gesellschaft, jedes mit einer spezifischen Rolle, die die Harmonie — oder das Ungleichgewicht — unserer Entscheidungen in der Natur widerspiegelt. Ihr Zustand zusammen mit ihrem Zweck bietet stille Führung.",
        fr: "Les organes du corps fonctionnent comme les membres d’une société, chacun ayant un rôle spécifique reflétant l’harmonie — ou le déséquilibre — de nos choix dans la nature. Leur état, combiné à leur fonction, offre une guidance silencieuse."
      }),
      items: [
        t({
          en: "A healthy heart, brain, or immune system shows alignment with equality, freedom, and nature's justice.",
          tr: "Sağlıklı bir kalp, beyin veya bağışıklık sistemi, eşitlik, özgürlük ve doğanın adaletiyle uyumu gösterir.",
          de: "Ein gesundes Herz, Gehirn oder Immunsystem zeigt die Übereinstimmung mit Gleichheit, Freiheit und der Gerechtigkeit der Natur.",
          fr: "Un cœur, un cerveau ou un système immunitaire sain montre l’alignement avec l’égalité, la liberté et la justice de la nature."
        }),
        t({
          en: "Illness signals misalignment, urging us to restore balance in our relationships with the environment and with one another.",
          tr: "Hastalık, uyumsuzluğun bir işaretidir.  Çevreyle ve birbirimizle olan ilişkilerimizdeki dengeyi yeniden sağlamamızı amaçlar.",
          de: "Krankheit signalisiert Fehlanpassung und drängt uns, das Gleichgewicht in unseren Beziehungen zur Umwelt und zueinander wiederherzustellen.",
          fr: "La maladie signale un désalignement et nous incite à rétablir l’équilibre dans nos relations avec l’environnement et les autres."
        }),
        t({
          en: "When alignment within nature is achieved, health naturally follows, and illness becomes rare — a reward for living in harmony with the principles that sustain life.",
          tr: "Doğayla uyum sağlandığında sağlık kendiliğinden gelir. Hastalık ise nadiren uğrar; bu, hayatı sürdüren ilkelerle uyum içinde yaşamanın bir ödülüdür.",
          de: "Wenn die Übereinstimmung mit der Natur erreicht wird, folgt die Gesundheit auf natürliche Weise, und Krankheit wird selten — eine Belohnung für das Leben im Einklang mit den Prinzipien, die das Leben erhalten.",
          fr: "Lorsque l’alignement avec la nature est atteint, la santé suit naturellement et la maladie devient rare — une récompense pour vivre en harmonie avec les principes qui soutiennent la vie."
        })
      ],
    },
    paragraph1: t({
      en: "Every human body begins life as a complex system, carrying the experiences, choices, and imprints of both the individual and their ancestors. Your body is the whole system, with each organ serving as a vital subsystem. Following the examples above, you can see that all genetic diseases and environmental disadvantages are related to actions taken in your environment by your ancestors and their interactions within nature. All diseases can be cured without any medicine when actions and interactions are healthy, and outcomes can flourish next generations for better.\n\n**When a virus, germ, or chemical enters the body, it moves along a path shaped by your choices and actions.** Persisting in harmful patterns allows it to sink deeper, reflecting the effects of your life on your body. As you come to understand your own system (life and environment) and guide your actions with awareness, healing, and renewal, the body gradually restores its balance. Recovery flows naturally from the harmony you cultivate within.\n\nSimilarly, **The Organ-Action-Result Analogy also applies to accidents.** Any damage your body sustains as a result of an accident is intended to teach you a lesson, reflecting the actions you took before the incident. The way an accident occurred explains your action that caused it.\n\nYour mental health is also deeply shaped by the consequences of your relationships. In nature, your memory, thoughts, emotions and feelings can be reshaped, challenged, or even erased to restore balance, justice, and joy for all.\n\nRemember, nature always offers the opportunity to make amends for your mistakes, though some errors may lead to irreversible losses. If you are harmed unjustly, those responsible will face consequences over time as you recover. **Personal opinions based on any belief or perspective may not align with nature's justice scale.** No technology exists — nor will it ever — that can stand in the way of nature's justice when it must prevail.",
      tr: "Her insan bedeni, hem bireyin hem de atalarının deneyimlerini, seçimlerini ve izlerini taşıyan karmaşık bir sistem olarak hayata başlar. Vücudunuz bütün bir sistemdir ve her organ, bu sistemin hayati bir alt sistemi olarak işlev görür. Yukarıda verilen örneklere bakarak, tüm genetik hastalıkların ve çevresel dezavantajların, atalarınızın çevrenizde gerçekleştirdiği eylemler ve doğayla etkileşimleriyle ilişkili olduğunu görebilirsiniz. Eylemler ve etkileşimler sağlıklı olduğunda tüm hastalıklar ilaç kullanılmadan tedavi edilebilir ve sonuçlar gelecek nesiller için daha iyiye doğru gelişim gösterir.\n\n**Bir virüs, mikrop veya kimyasal vücuda girdiğinde, seçimleriniz ve eylemlerinizle şekillenen bir yolda ilerler.** Zararlı davranış kalıplarında ısrar etmek, bunların daha derinlere işlemesine ve hayatınızın vücudunuz üzerindeki etkilerini yansıtmasına olanak tanır. Kendi sisteminizi (hayatınızı ve çevrenizi) anladıkça ve eylemlerinizi farkındalık, iyileşme ve yenilenme ile yönlendirdikçe, vücut yavaş yavaş dengesini yeniden kazanır. İyileşme, içinizde geliştirdiğiniz uyumdan doğal olarak kaynaklanır.\n\nBenzer şekilde, **Organ-Eylem-Sonuç Benzetmesi kazalar için de geçerlidir.** Yaşadığınız herhangi bir kaza sonucunda vücudunuzda oluşan hasarlar, kazadan önceki eylemlerinizin bir yansıması olarak size bir ders vermeyi amaçlar. Yaşanılan bir kazanın oluşma şekli, sebep olan eyleminizi açıklar.\n\nZihinsel sağlığınız da ilişkilerinizin sonuçlarından derin bir şekilde etkilenir. Doğada hafızanız, düşünceleriniz, duygularınız ve hisleriniz; dengeyi, adaleti ve herkes için neşeyi yeniden sağlamak amacıyla yeniden şekillendirilebilir, sınanabilir hatta silinebilir.\n\nUnutmayın ki doğa, her zaman hatalarınızı telafi etme fırsatını sunar. Bazı hatalar ise geri dönülemeyecek kayıplara yol açar. Haksız yere zarar görürseniz, iyileştikçe sorumlular zamanla sonuçlarıyla yüzleşecektir. **Herhangi bir inanç veya bakış açısına dayanan kişisel görüşler, doğanın adaletiyle (dengesiyle) örtüşmeyebilir.** Doğanın adaletinin tecelli etmesi gerektiği durumlarda önüne geçebilecek herhangi bir teknoloji ne şu an vardır ne de gelecekte olacaktır.",
      de: "Jeder menschliche Körper beginnt das Leben als ein komplexes System, das die Erfahrungen, Entscheidungen und Prägungen sowohl des Individuums als auch seiner Vorfahren trägt. Ihr Körper ist das gesamte System, wobei jedes Organ als lebenswichtiges Teilsystem dient. Anhand der obigen Beispiele lässt sich erkennen, dass alle genetischen Krankheiten und Umweltnachteile mit dem Verhalten unserer Vorfahren in unserer Umwelt und deren Interaktionen mit der Natur zusammenhängen. Alle Krankheiten können ohne Medikamente geheilt werden, wenn sie gesund sind und die Folgen für die nächsten Generationen positiv sind.\n\n**Wenn ein Virus, Keim oder eine Chemikalie in den Körper gelangt, bewegt es sich auf einem Weg, der durch Ihre Entscheidungen und Handlungen geformt wird.** Das Festhalten an schädlichen Mustern erlaubt es, tiefer einzudringen und die Auswirkungen Ihres Lebens auf Ihren Körper widerzuspiegeln. Wenn Sie beginnen, Ihr eigenes System (Leben und Umwelt) zu verstehen und Ihre Handlungen mit Bewusstsein, Heilung und Erneuerung leiten, stellt der Körper allmählich sein Gleichgewicht wieder her. Heilung fließt natürlich aus der Harmonie, die Sie in sich selbst kultivieren.\n\nÄhnlich gilt **die Organ-Handlung-Ergebnis-Analogie auch für Unfälle.** Jeder Schaden, den Ihr Körper durch einen Unfall erleidet, soll Ihnen eine Lektion erteilen und spiegelt die Handlungen wider, die Sie vor dem Vorfall unternommen haben. Die Art und Weise, wie ein Unfall passiert ist, erklärt Ihre Handlung, die ihn verursacht hat. \n\nIhre geistige Gesundheit wird auch stark von den Folgen Ihrer Beziehungen geprägt. In der Natur können Ihr Gedächtnis, Ihre Gedanken, Emotionen und Gefühle neu geformt, herausgefordert oder sogar ausgelöscht werden, um Gleichgewicht, Gerechtigkeit und Freude für alle wiederherzustellen.\n\nDenken Sie daran, dass die Natur immer die Möglichkeit bietet, Fehler wiedergutzumachen, auch wenn einige Fehler zu irreversiblen Verlusten führen können. Wenn Ihnen Unrecht zugefügt wird, werden diejenigen, die verantwortlich sind, im Laufe der Zeit die Konsequenzen tragen, während Sie sich erholen. **Persönliche Meinungen, die auf irgendeinem Glauben oder einer Perspektive basieren, stimmen möglicherweise nicht mit der Gerechtigkeitsskala der Natur überein.** Es gibt keine Technologie – und wird es auch niemals geben –, die sich der Gerechtigkeit der Natur in den Weg stellen kann, wenn sie sich durchsetzen muss.",
      fr: "Chaque corps humain commence la vie en tant que système complexe, portant les expériences, les choix et les empreintes à la fois de l'individu et de ses ancêtres. Votre corps est l'ensemble du système, chaque organe servant de sous-système vital. En suivant les exemples ci-dessus, vous constaterez que toutes les maladies génétiques et tous les désavantages environnementaux sont liés aux actions menées par vos ancêtres dans votre environnement et à leurs interactions avec la nature. Toutes les maladies peuvent être guéries sans médicament lorsque les actions et les interactions sont saines, et les résultats peuvent contribuer à l'épanouissement des générations futures.\n\n**Lorsqu'un virus, un germe ou un produit chimique pénètre dans le corps, il suit un chemin façonné par vos choix et actions.** Persister dans des schémas nuisibles permet à cela de s'enfoncer plus profondément, reflétant les effets de votre vie sur votre corps. À mesure que vous commencez à comprendre votre propre système (vie et environnement) et à guider vos actions avec conscience, guérison et renouveau, le corps restaure progressivement son équilibre. La récupération découle naturellement de l'harmonie que vous cultivez à l'intérieur.\n\nDe même, **l'analogie Organe-Action-Sonséquence s'applique également aux accidents.** Tout dommage que votre corps subit à la suite d'un accident est destiné à vous enseigner une leçon, reflétant les actions que vous avez entreprises avant l'incident. La façon dont un accident s'est produit explique votre action qui l'a causé.\n\nVotre santé mentale est également profondément façonnée par les conséquences de vos relations. Dans la nature, votre mémoire, vos pensées, vos émotions et vos sentiments peuvent être remodelés, remis en question, voire effacés pour rétablir l'équilibre, la justice et la joie pour tous.\n\nN'oubliez pas que la nature offre toujours l'occasion de réparer vos erreurs, bien que certaines erreurs puissent entraîner des pertes irréversibles. Si vous êtes lésé de manière injuste, les responsables feront face à des conséquences au fil du temps alors que vous vous rétablissez. **Les opinions personnelles basées sur une croyance ou une perspective quelconque peuvent ne pas être en accord avec l'échelle de justice de la nature.** Aucune technologie n'existe — et n'existera jamais — qui puisse faire obstacle à la justice de la nature lorsqu'elle doit prévaloir."
    }),
    examples: [
      t({
        en: "Weakened vision may reflect moments when you overlooked someone's needs or obstructed their path, mirroring times you turned a blind eye to their opportunities.",
        tr: "Zayıf görme yeteneği, birinin ihtiyaçlarını görmezden geldiğiniz veya yolunu engellediğiniz anları, yani onların fırsatlarına göz yumduğunuz zamanları yansıtabilir.",
        de: "Geschwächtes Sehvermögen kann Momente widerspiegeln, in denen Sie die Bedürfnisse von jemandem übersehen oder seinen Weg blockiert haben, und damit Zeiten widerspiegeln, in denen Sie ihre Chancen ignoriert haben.",
        fr: "Une vision affaiblie peut refléter les moments où vous avez ignoré les besoins de quelqu’un ou entravé son chemin, reflétant les fois où vous avez fermé les yeux sur ses opportunités."
      }),
      t({
        en: "If your hearing has diminished, it may reflect times when you ignored someone’s voice or cry for help, or when you silenced another’s freedom to be heard.",
        tr: "İşitme duyunuz azaldıysa, bu durum birinin sesini veya yardım çığlığını görmezden geldiğiniz veya bir başkasının duyulma özgürlüğünü susturduğunuz zamanları yansıtıyor olabilir.",
        de: "Wenn Ihr Gehör nachgelassen hat, kann es Zeiten widerspiegeln, in denen Sie die Stimme oder den Hilferuf von jemandem ignoriert haben oder als Sie die Freiheit eines anderen, gehört zu werden, zum Schweigen gebracht haben.",
        fr: "Si votre audition a diminué, cela peut refléter les moments où vous avez ignoré la voix ou l’appel à l’aide de quelqu’un, ou lorsque vous avez réduit au silence la liberté d’un autre d’être entendu."
      }),
      t({
        en: "If you've experienced a heart attack, it may symbolize the ways your actions, choices, or neglect have created struggles or obstacles in another being's life.",
        tr: "Eğer kalp krizi geçirdiyseniz, bu durum eylemlerinizin, seçimlerinizin veya ihmallerinizin başka bir canlının hayatında mücadelelere veya engellere yol açmasının sembolü olabilir.",
        de: "Wenn Sie einen Herzinfarkt erlitten haben, kann dies die Weise symbolisieren, wie Ihre Handlungen, Entscheidungen oder Ihr Versäumnis Kämpfe oder Hindernisse im Leben eines anderen Wesens geschaffen haben.",
        fr: "Si vous avez eu une crise cardiaque, cela peut symboliser la manière dont vos actions, choix ou négligences ont créé des difficultés ou des obstacles dans la vie d’un autre être."
      }),
      t({
        en: "If you've experienced a form of cancer, it may symbolize the harm or suffering you once caused — perhaps taking a life or inflicting deep pain on another living being.",
        tr: "Eğer bir kanser türü geçirdiyseniz, bu bir zamanlar neden olduğunuz zararı veya acıyı sembolize ediyor olabilir; belki bir canı aldınız veya başka bir canlıya derin acı verdiniz.",
        de: "Wenn Sie eine Form von Krebs erlebt haben, kann dies den Schaden oder das Leid symbolisieren, das Sie einst verursacht haben — vielleicht das Nehmen eines Lebens oder das Zufügen tiefen Schmerzes einem anderen Lebewesen.",
        fr: "Si vous avez eu une forme de cancer, cela peut symboliser le mal ou la souffrance que vous avez causés autrefois — peut-être en prenant une vie ou en infligeant une profonde douleur à un autre être vivant."
      })
    ],
  },
} satisfies Dictionary;

export default pageContent;
