import { t, type Dictionary } from "intlayer";

const pageContent = {
  key: "interconnectedness-section",
  content: {
    title: t({
      en: "Interconnectedness:\nA Unified Being",
      tr: "Bütünlük: Birleşik Bir Varlık",
      de: "Verbundenheit:\nEin vereintes Wesen",
      fr: "Interconnexion :\nUn être unifié"
    }),
    quote: t({
      en: "Our lives are not private possessions but parts of a larger whole. Just as organs in a body depend on one another, all beings depend on each other through relationships both visible and unseen.",
      tr: "Hayatlarımız özel mülkler değil, daha büyük bir bütünün parçalarıdır. Tıpkı bir vücuttaki organların birbirine bağımlı olması gibi, tüm varlıklar da görünür ve görünmez ilişkiler aracılığıyla birbirlerine bağımlıdır.",
      de: "Unser Leben ist kein privater Besitz, sondern Teil eines größeren Ganzen. So wie Organe in einem Körper voneinander abhängen, sind alle Wesen durch sichtbare und unsichtbare Beziehungen miteinander verbunden.",
      fr: "Nos vies ne sont pas des possessions privées mais des parties d’un tout plus vaste. Tout comme les organes d’un corps dépendent les uns des autres, tous les êtres dépendent les uns des autres à travers des relations visibles et invisibles."
    }),
    description: t({
      en: "We all live on Earth, a tiny realm within the boundless universe. Every being is part of a living whole that is called nature. When one living being suffers, the effects rarely stop with them; families, communities, and ecosystems are drawn into the wave. When one living being thrives, the benefits ripple outward too. Interconnectedness means our lives are not private possessions but shared currents in a greater flow. The health of the whole system mirrors the health of each part — and vice versa.\n\nTo feel your connection with the world, notice both your surroundings and what you create. Every word, movement, thought, or artwork reflects the life around you. Observing your creations with care and attention to detail reveals your harmony with the world.",
      tr: "Hepimiz, sınırsız evrenin içindeki küçücük bir alan olan Dünya'da yaşıyoruz. Her varlık, doğa adı verilen canlı bir bütünün parçasıdır. Bir canlı acı çektiğinde, etkileri nadiren onunla biter; aileler, topluluklar ve ekosistemler de bu dalgaya kapılır. Bir canlı geliştiğinde, faydaları da dışarıya yayılır. Birbirine bağlılık, hayatlarımızın özel mülkler değil, daha büyük bir akışta paylaşılan akıntılar olduğu anlamına gelir. Tüm sistemin sağlığı, her bir parçanın sağlığını yansıtır — ve bunun tersi de geçerlidir.\n\nDünyayla bağlantınızı hissetmek için hem çevrenize hem yaratımlarınıza yönelik farkındalık edinmelisiniz. Her kelime, hareket, düşünce veya sanat eseri, etrafınızdaki yaşamı yansıtır. Yaratımlarınızı özenle ve ayrıntılara dikkat ederek incelemek, dünyayla uyumunuzu ortaya çıkarmaya yardımcı olur.",
      de: "Wir alle leben auf der Erde, einem winzigen Bereich im grenzenlosen Universum. Jedes Wesen ist Teil eines lebendigen Ganzen, das Natur genannt wird. Wenn ein Lebewesen leidet, enden die Auswirkungen selten bei ihm; Familien, Gemeinschaften und Ökosysteme werden mit hineingezogen. Wenn ein Lebewesen gedeiht, breiten sich die Vorteile ebenfalls aus. Verbundenheit bedeutet, dass unser Leben kein privater Besitz ist, sondern geteilte Strömungen in einem größeren Fluss. Die Gesundheit des gesamten Systems spiegelt die Gesundheit jedes Teils wider – und umgekehrt.\n\nUm deine Verbindung mit der Welt zu spüren, achte sowohl auf deine Umgebung als auch auf das, was du erschaffst. Jedes Wort, jede Bewegung, jeder Gedanke oder jedes Kunstwerk spiegelt das Leben um dich herum wider. Wenn du deine Schöpfungen aufmerksam und sorgfältig betrachtest, zeigt sich deine Harmonie mit der Welt.",
      fr: "Nous vivons tous sur Terre, un minuscule royaume au sein de l’univers infini. Chaque être fait partie d’un tout vivant appelé la nature. Lorsqu’un être vivant souffre, les effets ne s’arrêtent que rarement à lui ; familles, communautés et écosystèmes sont entraînés dans la vague. Lorsqu’un être vivant prospère, les bienfaits se propagent également. L’interconnexion signifie que nos vies ne sont pas des possessions privées mais des courants partagés dans un flux plus vaste. La santé du système tout entier reflète la santé de chaque partie — et inversement.\n\nPour ressentir votre connexion avec le monde, portez attention à la fois à votre environnement et à ce que vous créez. Chaque mot, mouvement, pensée ou œuvre d’art reflète la vie qui vous entoure. Observer vos créations avec soin et attention aux détails révèle votre harmonie avec le monde."
    }),
    experiment: {
      title: t({
        en: "You can try this example experiment",
        tr: "Bu örnek deneyi deneyebilirsiniz",
        de: "Du kannst dieses Beispiel-Experiment ausprobieren",
        fr: "Vous pouvez essayer cette expérience exemple"
      }),
      description: t({
        en: "Cover your ears to block out distractions and focus on your creation, then begin creating —writing, painting, or making music— within a room. Record your process, capturing your computer screen, your environment, or both. While you focus on your creation (output), let other people or animals move freely through the space (your room, house, and even garden), without restrictions. After an hour, review the recordings and your creations carefully. You will notice how the presence of others —their movements, conversations, choices, memories, and even subtle thoughts— has left traces within your creation, quietly but visibly shaping the outcome of your creative expressions.",
        tr: "Dikkatinizi dağıtan unsurları engellemek için kulaklık takın ve tamamen üretiminize odaklanın; ardından bir odada yazı yazarak, resim yaparak veya müzik üreterek yaratıcılığınıza odaklanın. Sürecinizi kaydedin; bilgisayarınızın ekranını, bulunduğunuz ortamı ya da her ikisini birden kayda alın. Siz üretiminize (çıktınıza) odaklanırken, diğer insanların odanızda, evinizde hatta bahçenizde serbestçe dolaşmalarına, hiçbir kısıtlama olmadan hareket etmelerine izin verin. Bir saat sonra, hem kayıtları hem de ürettiklerinizi dikkatlice inceleyin. Diğer insanların varlığının —hareketlerinin, konuşmalarının, seçimlerinin, anılarının ve hatta en ince düşüncelerinin— yaratım sürecinize nasıl izler bıraktıklarını, sessiz ama görünür bir şekilde yaratıcı ifadelerinizin sonucunu nasıl şekillendirdiklerini fark edeceksiniz.",
        de: "Bedecke deine Ohren, um Ablenkungen auszublenden, und konzentriere dich auf deine Schöpfung. Beginne dann zu erschaffen – zu schreiben, zu malen oder Musik zu machen – in einem Raum. Nimm deinen Prozess auf, indem du deinen Computerbildschirm, deine Umgebung oder beides aufzeichnest. Während du dich auf deine Schöpfung konzentrierst, lass andere Menschen oder Tiere sich frei im Raum (dein Zimmer, Haus oder sogar Garten) bewegen, ohne Einschränkungen. Nach einer Stunde überprüfe die Aufnahmen und deine Werke sorgfältig. Du wirst bemerken, wie die Anwesenheit anderer – ihre Bewegungen, Gespräche, Entscheidungen, Erinnerungen und sogar subtile Gedanken – Spuren in deiner Schöpfung hinterlassen hat und das Ergebnis deiner kreativen Ausdrucksformen leise, aber sichtbar geprägt hat.",
        fr: "Bouchez-vous les oreilles pour bloquer les distractions et concentrez-vous sur votre création, puis commencez à créer — écrire, peindre ou faire de la musique — dans une pièce. Enregistrez votre processus, capturez l’écran de votre ordinateur, votre environnement ou les deux. Pendant que vous vous concentrez sur votre création (production), laissez d’autres personnes ou animaux se déplacer librement dans l’espace (votre chambre, maison, voire jardin), sans restrictions. Après une heure, examinez attentivement les enregistrements et vos créations. Vous remarquerez comment la présence des autres — leurs mouvements, conversations, choix, souvenirs et même pensées subtiles — a laissé des traces dans votre création, façonnant silencieusement mais visiblement le résultat de vos expressions créatives."
      }),
    },
    paragraph1: t({
      en: "Most lives begin in a womb, yet even there, no being develops in isolation. Just as in the example experiment, where every presence subtly influences a creation, a baby's genetic development is shaped not only by the parents' actions and intentions but also by the wider web of relationships surrounding them. Connections with other humans, animals, and nature all leave their imprint, weaving together the baby's physical and energetic makeup. In this way, every life emerges as a reflection of the shared harmony and influences of its environment.\n\nWe all move through life guided by our feelings, carried along by a greater flow that connects us all. Our emotions are intertwined beyond time and space, reaching far past our immediate surroundings. A song carries the singer's emotions across distance and years; in an online chatroom, you can sense others' feelings even without seeing their faces or talking to them; sometimes, you suddenly feel anxious because somewhere, unseen, someone is about to be hurt...",
      tr: "Çoğu yaşam rahimde başlar, ancak orada bile hiçbir varlık tek başına gelişmez. Tıpkı her varlığın bir yaratılışı incelikle etkilediği örnek deneyde olduğu gibi, bir bebeğin genetik gelişimi yalnızca ebeveynlerin eylemleri ve niyetleri tarafından değil, aynı zamanda onları çevreleyen daha geniş ilişki ağı (bütünlük) tarafından da şekillendirilir. Diğer insanlarla, hayvanlarla ve doğayla kurulan ilişkiler, bebeğin fiziksel (genetik) ve enerjik yapısını örerek izlerini bırakır. Bu şekilde, her yaşam, çevresinin ortak uyumunun ve etkilerinin bir yansıması olarak ortaya çıkar.\n\nHepimiz duygularımızın rehberliğinde, hepimizi birbirine bağlayan daha büyük bir akışla sürüklenerek hayatımızı sürdürürüz. Duygularımız zaman ve mekanın ötesinde iç içe geçmiş, yakın çevremizin çok ötesine ulaşır. Bir şarkı, şarkıcının duygularını mesafelere ve yıllara taşır; çevrimiçi bir sohbet odasında, yüzlerini görmeden veya onlarla konuşmadan bile başkalarının duygularını hissedebilirsiniz; bazen, görünmeyen bir yerde, birinin incinmek üzere olduğunu hissettiğiniz için durduk yere endişe hissine kapılabilirsiniz...",
      de: "Die meisten Leben beginnen im Mutterleib, doch selbst dort entwickelt sich kein Wesen isoliert. Genau wie in dem Beispiel-Experiment, in dem jede Präsenz eine Schöpfung subtil beeinflusst, wird die genetische Entwicklung eines Babys nicht nur von den Handlungen und Absichten der Eltern, sondern auch vom weiteren Beziehungsnetz um sie herum geprägt. Verbindungen zu anderen Menschen, Tieren und der Natur hinterlassen alle ihre Spuren und verweben die physische und energetische Struktur des Babys. Auf diese Weise entsteht jedes Leben als Spiegelbild der gemeinsamen Harmonie und Einflüsse seiner Umgebung.\n\nWir alle bewegen uns durchs Leben, geleitet von unseren Gefühlen, getragen von einem größeren Fluss, der uns alle verbindet. Unsere Emotionen sind jenseits von Zeit und Raum miteinander verflochten und reichen weit über unsere unmittelbare Umgebung hinaus. Ein Lied trägt die Emotionen des Sängers über Entfernungen und Jahre hinweg; in einem Online-Chatroom kannst du die Gefühle anderer spüren, selbst ohne ihre Gesichter zu sehen oder mit ihnen zu sprechen; manchmal fühlst du dich plötzlich ängstlich, weil irgendwo, unsichtbar, jemand kurz davor ist, verletzt zu werden...",
      fr: "La plupart des vies commencent dans un ventre, mais même là, aucun être ne se développe isolément. Comme dans l’expérience exemple, où chaque présence influence subtilement une création, le développement génétique d’un bébé est façonné non seulement par les actions et intentions des parents, mais aussi par le vaste réseau de relations qui les entoure. Les liens avec d’autres humains, animaux et la nature laissent tous leur empreinte, tissant ensemble la constitution physique et énergétique du bébé. Ainsi, chaque vie émerge comme le reflet de l’harmonie partagée et des influences de son environnement.\n\nNous avançons tous dans la vie guidés par nos sentiments, portés par un courant plus vaste qui nous relie tous. Nos émotions sont entremêlées au-delà du temps et de l’espace, atteignant bien au-delà de notre environnement immédiat. Une chanson porte les émotions du chanteur à travers la distance et les années ; dans un salon de discussion en ligne, vous pouvez ressentir les émotions des autres sans voir leurs visages ni leur parler ; parfois, vous vous sentez soudainement anxieux parce que quelque part, invisible, quelqu’un est sur le point d’être blessé..."
    }) 
  },
} satisfies Dictionary;

export default pageContent;
