import { t, type Dictionary } from "intlayer";

const pageContent = {
  key: "interconnectedness-section",
  content: {
    title: t({
      en: "Interconnectedness:\nA Unified Being",
      tr: "Bütünlük: Birleşik Bir Yaşam",
      de: "Verbundenheit:\nEin vereintes Wesen",
      fr: "Interconnexion :\nUn être unifié"
    }),
    quote: t({
      en: "Just as the organs in a body are dependent on each other, all living beings are also dependent on one another through visible and invisible connections.",
      tr: "Tıpkı bir vücuttaki organların birbirlerine bağımlı olması gibi, tüm canlılar da görünür ve görünmez bağlar aracılığıyla birbirlerine bağımlıdır.",
      de: "So wie die Organe eines Körpers voneinander abhängig sind, sind auch alle Lebewesen durch sichtbare und unsichtbare Verbindungen voneinander abhängig.",
      fr: "Tout comme les organes d'un corps dépendent les uns des autres, tous les êtres vivants dépendent également les uns des autres à travers des liens visibles et invisibles."
    }),
    description: t({
      en: "We are all trying to live by feeling nature within a tiny part of the infinite universe, which we define as Earth. To better understand the harmony between our mind and body, we need to approach our observations as a small reflection of nature from a broader perspective. **Rather than egocentric approaches, we can gain awareness of the depth of our connection with nature by paying attention to the details of our environment and creations.** Because every action performed also reflects the details of the life around it. Every sound, movement, word, thought, and piece of art is interconnected. So, how can we make this connection visible?",
      tr: "Hepimiz, sınırsız evrenin içinde küçücük bir alan olan ve Dünya olarak tanımladığımız bir bütünde doğayı hissederek yaşamaya çalışıyoruz. Zihnimizin vücudumuzla olan uyumunu daha iyi kavrayabilmek için, doğanın küçük bir iz düşümü olarak, gözlemlerimizi daha geniş bir bakış açısıyla ele almamız gerekiyor. **Benmerkezci yaklaşımlardan ziyade, çevremizin ve yaratımlarımızın ayrıntılarına dikkat ederek doğayla olan bağımızın derinliğine yönelik farkındalık kazanabiliriz.** Çünkü gerçekleştirilen her eylem aynı zamanda çevresindeki yaşamın detaylarını yansıtır. Her ses, hareket, kelime, düşünce ve sanat eseri birbirine bağlıdır. Peki, bu bağı nasıl görünür kılabiliriz?",
      de: "Wir versuchen alle, die Natur innerhalb eines winzigen Bereichs des unendlichen Universums, das wir Erde nennen, zu spüren und zu leben. Um die Harmonie zwischen unserem Geist und Körper besser zu verstehen, müssen wir unsere Beobachtungen als kleinen Abglanz der Natur aus einer breiteren Perspektive betrachten. **Statt egozentrischer Ansätze können wir ein Bewusstsein für die Tiefe unserer Verbindung mit der Natur gewinnen, indem wir auf die Details unserer Umwelt und unserer Schöpfungen achten.** Denn jede Handlung spiegelt auch die Details des Lebens in ihrer Umgebung wider. Jeder Ton, jede Bewegung, jedes Wort, jeder Gedanke und jedes Kunstwerk ist miteinander verbunden. Wie können wir also diese Verbindung sichtbar machen?",
      fr: "Nous essayons tous de vivre en ressentant la nature dans une minuscule partie de l'univers infini que nous appelons Terre. Pour mieux comprendre l'harmonie entre notre esprit et notre corps, nous devons aborder nos observations comme un petit reflet de la nature avec une perspective plus large. **Plutôt que des approches égocentriques, nous pouvons prendre conscience de la profondeur de notre lien avec la nature en prêtant attention aux détails de notre environnement et de nos créations.** Car chaque action réalisée reflète également les détails de la vie qui l'entoure. Chaque son, mouvement, mot, pensée et œuvre d'art est interconnecté. Alors, comment pouvons-nous rendre ce lien visible ?"
    }),
    experiment: {
      title: t({
        en: "This sample experiment can help you gain awareness",
        tr: "Bu örnek deney farkındalık kazanmanıza yardımcı olabilir",
        de: "Dieses Beispielexperiment kann Ihnen helfen, Bewusstsein zu erlangen",
        fr: "Cette expérience exemple peut vous aider à prendre conscience"
      }),
      description: t({
        en: "Put on headphones to limit distractions. Use visual recording devices to capture the place you are in and the area you want to observe. Focusing your mind on yourself, start speaking, writing, drawing, or creating music in the room. While you are engaged in your creation, allow other beings to perform the actions they want in your room, home, garden, or street. Continue this experiment for a while. After the process, carefully examine your recorded creations. You may notice the harmony between a word you spoke, a movement you made, a mistake you committed, or a choice you took and other beings. The color choices, movements, speech, and even thoughts of those beings you do not hear or see are reflected in every form of your creation. In this way, you can realize that through your own existence, you also reflect the traces of beings around you.",
        tr: "Dikkatinizi dağıtan unsurları kısıtlamak için kulaklık takın. Bulunduğunuz yeri ve gözlemlemek istediğiniz alanı görsel kaydediciler kullanarak kayıt altına alın. Zihninizi kendinize odaklayarak bulunduğunuz odada konuşmaya, yazı yazmaya, resim yapmaya veya müzik üretmeye başlayın. Siz yaratımınızla uğraşırken, diğer canlıların odanızda, evinizde, bahçenizde veya sokağınızda istedikleri eylemleri gerçekleştirmelerini isteyin. Bir süre boyunca bu deneyi devam ettirin. Sürecin ardından kaydettiğiniz yaratımlarınızı dikkatlice inceleyin. Söylediğiniz bir kelimenin, uyguladığınız bir hareketin, yaptığınız bir hatanın veya gerçekleştirdiğiniz bir seçimin diğer canlılarla olan ahengini görebilirsiniz. Duymadığınız ve görmediğiniz o canlıların renk seçimleri, hareketleri, konuşmaları ve hatta düşünceleri sizin yaratımınızın her biçimine yansımıştır. Böylece kendi varlığınız aracılığıyla etrafınızdaki varlıkların izlerini de yansıttığınızı fark edebilirsiniz.",
        de: "Setzen Sie Kopfhörer auf, um Ablenkungen zu begrenzen. Verwenden Sie visuelle Aufnahmegeräte, um den Ort, an dem Sie sich befinden, und den Bereich, den Sie beobachten möchten, aufzuzeichnen. Konzentrieren Sie Ihren Geist auf sich selbst und beginnen Sie im Raum zu sprechen, zu schreiben, zu zeichnen oder Musik zu machen. Während Sie mit Ihrer Schöpfung beschäftigt sind, lassen Sie andere Lebewesen die Handlungen ausführen, die sie in Ihrem Zimmer, Zuhause, Garten oder auf der Straße ausführen möchten. Führen Sie dieses Experiment eine Weile fort. Untersuchen Sie anschließend Ihre aufgezeichneten Schöpfungen sorgfältig. Sie können die Harmonie zwischen einem Wort, das Sie gesagt haben, einer Bewegung, die Sie gemacht haben, einem Fehler, den Sie begangen haben, oder einer getroffenen Entscheidung und anderen Lebewesen erkennen. Die Farbwahl, Bewegungen, Sprache und sogar Gedanken derjenigen Lebewesen, die Sie nicht hören oder sehen, spiegeln sich in jeder Form Ihrer Schöpfung wider. Auf diese Weise können Sie erkennen, dass Sie durch Ihre eigene Existenz auch die Spuren der Lebewesen um Sie herum widerspiegeln.",
        fr: "Mettez des écouteurs pour limiter les distractions. Utilisez des dispositifs d'enregistrement visuel pour capturer l'endroit où vous vous trouvez et la zone que vous souhaitez observer. En concentrant votre esprit sur vous-même, commencez à parler, écrire, dessiner ou créer de la musique dans la pièce. Pendant que vous êtes absorbé par votre création, laissez les autres êtres réaliser les actions qu'ils souhaitent dans votre chambre, votre maison, votre jardin ou dans la rue. Continuez cette expérience pendant un certain temps. Après le processus, examinez attentivement vos créations enregistrées. Vous pouvez observer l'harmonie entre un mot que vous avez prononcé, un mouvement que vous avez effectué, une erreur que vous avez commise ou un choix que vous avez pris et les autres êtres. Les choix de couleurs, les mouvements, la parole et même les pensées de ces êtres que vous n'entendez ni ne voyez se reflètent dans chaque forme de votre création. Ainsi, vous pouvez prendre conscience qu'à travers votre propre existence, vous reflétez également les traces des êtres qui vous entourent."
      }),
    },
    paragraph1: t({
      en: "Mind mediates human imagination as a mixture of numbers and letters. Intelligence, on the other hand, is the ultimate outcome of life experiences in the mind. When we become aware of the perspective of wholeness, we can see how the life journey that begins in the womb takes shape. The ways (actions) parents form connections with their environment and the choices of living beings in that environment are reflected in the genetic sequence of a baby. As a small reflection of nature, every baby visibly carries the traces of both their near and distant surroundings. Mental and physical development is shaped in a similar context throughout a person's life. Our emotions, beyond time and space, reflect onto each other in an intertwined manner. Consequently, our life connections are multifaceted. Our senses, which can make invisible connections with each other visible, prove the wholeness of life to us in different ways.\n\nThe emotional states of viewers watching an online broadcast reflect the broadcaster's feelings, even if they are not talking to each other; while you are at home thinking about which song to play, the presence of a passerby on the street inspires (or serves as a means for) your choice; the stress of someone at the store where you shop can reflect on you as unexpected sweating; the set of emotions present in a previously recorded broadcast will also reflect the feelings of those who watch it or were present during its recording; any product you use carries all the emotional sets experienced during its production... We can multiply these examples by reinterpreting the details of our lives. In fact, every moment is filled with unseen life miracles.",
      tr: "Akıl, rakam ve harflerin bir karışımı olarak insanın hayal gücüne aracılık eder. Zekâ ise zihindeki yaşam tecrübesinin son ucudur. Bütünlük bakış açısını fark ettiğimizde, rahimde başlayan yaşam yolculuğunun nasıl şekil aldığını görebiliriz. Ebeveynlerin çevreleriyle olan bağ kurma biçimleri (eylemleri) ve çevredeki canlıların seçimleri bir bebeğin genlerindeki dizilime yansır. Doğanın küçük bir iz düşümü olarak, her bebek hem yakın hem uzak çevresinin izlerini görünür biçimde taşır. Zihinsel ve fiziksel gelişim insanın tüm yaşam sürecinde benzer bağlamda şekil alır. Hislerimiz, zamanın ve mekanın ötesinde, iç içe geçmiş bir biçimde birbirimize yansır. Haliyle yaşam bağlarımız çok yönlüdür. Birbirimizle olan görünmez bağları görünür kılabilen duyularımız, farklı şekillerde yaşamın bütünlüğünü bize kanıtlar.\n\nBir internet yayınını izleyenlerin duygu durumları, birbirleriyle konuşmuyor olsalar bile, yayıncının hislerine yansır; siz evinizde öylece hangi şarkıyı çalacağınızı düşünürken sokaktan geçen birinin varlığı seçiminize ilham (veya vesile) olur; alışveriş yaptığınız marketteki birinin stresi size durduk yere terlemek olarak yansır; geçmiş zamanda kaydedilen bir yayında mevcut olan his kümesi, o yayını izleyenlerin veya çekim esnasında orada bulunanların hislerini de gelecekte bize yansıtır; kullandığınız herhangi bir ürün, üretimi esnasında yaşanan tüm his kümelerini beraberinde getirir... Örnekleri hayatımızın detaylarını tekrar yorumlayarak çoğaltabiliriz. Aslında her an görmediğimiz yaşam mucizeleriyle doludur.",
      de: "Der Verstand vermittelt der menschlichen Vorstellungskraft als Mischung aus Zahlen und Buchstaben. Intelligenz hingegen ist das ultimative Ergebnis der Lebenserfahrungen im Geist. Wenn wir uns der Perspektive der Ganzheit bewusst werden, können wir sehen, wie sich der Lebensweg, der im Mutterleib beginnt, formt. Die Art und Weise (Handlungen), wie Eltern Verbindungen zu ihrer Umgebung herstellen, und die Entscheidungen der Lebewesen in dieser Umgebung spiegeln sich in der genetischen Sequenz eines Babys wider. Als kleiner Abglanz der Natur trägt jedes Baby sichtbar die Spuren seiner nahen und fernen Umgebung. Mentale und physische Entwicklung wird im Verlauf des gesamten Lebens in einem ähnlichen Kontext geformt. Unsere Gefühle spiegeln sich über Zeit und Raum hinweg ineinander. Folglich sind unsere Lebensverbindungen vielfältig. Unsere Sinne, die unsichtbare Verbindungen sichtbar machen können, beweisen uns die Ganzheit des Lebens auf unterschiedliche Weise.\n\nDie emotionalen Zustände der Zuschauer eines Online-Streams spiegeln die Gefühle des Senders wider, auch wenn sie nicht miteinander sprechen; während Sie zu Hause darüber nachdenken, welchen Song Sie spielen möchten, inspiriert (oder dient als Mittel) die Anwesenheit eines Passanten auf der Straße Ihre Wahl; der Stress einer Person im Supermarkt, in dem Sie einkaufen, spiegelt sich bei Ihnen als plötzliches Schwitzen wider; das in der Vergangenheit aufgezeichnete Emotionsset eines Streams wird auch die Gefühle derjenigen widerspiegeln, die ihn sehen oder während der Aufnahme anwesend waren; jedes von Ihnen verwendete Produkt trägt alle während der Produktion erlebten Emotionen mit sich... Wir können diese Beispiele vervielfachen, indem wir die Details unseres Lebens neu interpretieren. Tatsächlich ist jeder Moment voller unsichtbarer Lebenswunder.",
      fr: "L'esprit sert d'intermédiaire à l'imagination humaine en tant que mélange de chiffres et de lettres. L'intelligence, quant à elle, est le résultat ultime de l'expérience de vie dans l'esprit. Lorsque nous prenons conscience de la perspective de la totalité, nous pouvons voir comment le parcours de vie qui commence dans l'utérus prend forme. Les manières (actions) dont les parents établissent des liens avec leur environnement et les choix des êtres vivants dans cet environnement se reflètent dans la séquence génétique d'un bébé. Comme un petit reflet de la nature, chaque bébé porte visiblement les traces de son environnement proche et lointain. Le développement mental et physique se forme dans un contexte similaire tout au long de la vie. Nos émotions, au-delà du temps et de l'espace, se reflètent les unes dans les autres de manière imbriquée. Par conséquent, nos liens de vie sont multiples. Nos sens, capables de rendre visibles les liens invisibles entre nous, nous prouvent l'unité de la vie de différentes manières.\n\nLes états émotionnels des spectateurs d'une diffusion en ligne reflètent les sentiments de l'émetteur, même s'ils ne se parlent pas entre eux; alors que vous réfléchissez chez vous à la chanson à jouer, la présence d'un passant dans la rue inspire (ou sert de moyen) votre choix; le stress d'une personne dans le supermarché où vous faites vos courses se reflète sur vous sous forme de transpiration soudaine; l'ensemble des émotions présentes dans une diffusion enregistrée dans le passé reflète également les sentiments de ceux qui la regardent ou étaient présents lors du tournage; tout produit que vous utilisez transporte toutes les émotions vécues lors de sa production... Nous pouvons multiplier ces exemples en réinterprétant les détails de notre vie. En réalité, chaque instant est rempli de miracles de vie invisibles."
    }) 
  },
} satisfies Dictionary;

export default pageContent;
